### ISSUE TITLE
Expected selector, but <delimiter "(" at 0> found.

### ISSUE THREAD

**Issue by RitterKnightCreative** [mmikkel/Retcon-Craft#4]
Just upgraded to 2.0.   Using this example snippet from the [srcSet docs](https://github.com/mmikkel/Retcon-Craft/wiki/srcset) seems to break Symfony:

```
{{ entry.body|retconSrcset(
    [
        {width: 375},
        {width: 480},
        {width: 768}
    ],
    '(min-width: 40em) 80vw, 100vw'
) }}
```

Now getting a Symfony XPath error, "expected selector", but <delimiter "(" at 0> found.

Tried adding an "img" selector, for example, to the 3rd parameter has no effect and gives the same error.

Not sure of it's related to #2, I see the first paragraph tag from the field is being based in (see line #10).

```Symfony\Component\CssSelector\Exception\SyntaxErrorException: Expected selector, but <delimiter "(" at 0> found. in /home/client/vendor/symfony/css-selector/Exception/SyntaxErrorException.php:34
Stack trace:
#0 /home/client/vendor/symfony/css-selector/Parser/Parser.php(283): Symfony\Component\CssSelector\Exception\SyntaxErrorException::unexpectedToken('selector', Object(Symfony\Component\CssSelector\Parser\Token))
#1 /home/client/vendor/symfony/css-selector/Parser/Parser.php(142): Symfony\Component\CssSelector\Parser\Parser->parseSimpleSelector(Object(Symfony\Component\CssSelector\Parser\TokenStream))
#2 /home/client/vendor/symfony/css-selector/Parser/Parser.php(118): Symfony\Component\CssSelector\Parser\Parser->parserSelectorNode(Object(Symfony\Component\CssSelector\Parser\TokenStream))
#3 /home/client/vendor/symfony/css-selector/Parser/Parser.php(53): Symfony\Component\CssSelector\Parser\Parser->parseSelectorList(Object(Symfony\Component\CssSelector\Parser\TokenStream))
#4 /home/client/vendor/symfony/css-selector/XPath/Translator.php(296): Symfony\Component\CssSelector\Parser\Parser->parse('(min-width: 40e...')
#5 /home/client/vendor/symfony/css-selector/XPath/Translator.php(122): Symfony\Component\CssSelector\XPath\Translator->parseSelectors('(min-width: 40e...')
#6 /home/client/vendor/symfony/css-selector/CssSelectorConverter.php(63): Symfony\Component\CssSelector\XPath\Translator->cssToXPath('(min-width: 40e...', 'descendant-or-s...')
#7 /home/client/vendor/symfony/dom-crawler/Crawler.php(704): Symfony\Component\CssSelector\CssSelectorConverter->toXPath('(min-width: 40e...')
#8 /home/client/vendor/mmikkel/retcon/src/library/RetconDom.php(64): Symfony\Component\DomCrawler\Crawler->filter('(min-width: 40e...')
#9 /home/client/vendor/mmikkel/retcon/src/services/RetconService.php(158): mmikkel\retcon\library\RetconDom->filter('(min-width: 40e...')
#10 /home/client/storage/runtime/compiled_templates/f3/f3abfd0b6beea298d74e7f66da771253da717dda31af8c04874c0826523557f6.php(47): mmikkel\retcon\services\RetconService->srcset('<p>Big projects...', Array, '(min-width: 40e...')
#11 /home/client/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_9d02a8153d01eefb63a2e466721d3626e72f469feaf36dc656af69bd0cde2277->block_content(Array, Array)
#12 /home/client/storage/runtime/compiled_templates/37/37abbda5ac6a809e6bae8dfaacb52a51db62fd35806c484b954befd18720c1cc.php(890): Twig_Template->displayBlock('content', Array, Array)
#13 /home/client/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_8e75b195c4c7e0a6e0464daa30863fde4e1cfec36948495a41f80552a7f05440->doDisplay(Array, Array)
#14 /home/client/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#15 /home/client/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#16 /home/client/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#17 /home/client/storage/runtime/compiled_templates/f3/f3abfd0b6beea298d74e7f66da771253da717dda31af8c04874c0826523557f6.php(28): craft\web\twig\Template->display(Array, Array)
#18 /home/client/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_9d02a8153d01eefb63a2e466721d3626e72f469feaf36dc656af69bd0cde2277->doDisplay(Array, Array)
#19 /home/client/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#20 /home/client/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#21 /home/client/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#22 /home/client/vendor/twig/twig/lib/Twig/Template.php(375): craft\web\twig\Template->display(Array)
#23 /home/client/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#24 /home/client/vendor/craftcms/cms/src/web/View.php(330): Twig_Environment->render('services/_entry', Array)
#25 /home/client/vendor/craftcms/cms/src/web/View.php(377): craft\web\View->renderTemplate('services/_entry', Array)
#26 /home/client/vendor/craftcms/cms/src/web/Controller.php(155): craft\web\View->renderPageTemplate('services/_entry', Array)
#27 /home/client/vendor/craftcms/cms/src/controllers/TemplatesController.php(78): craft\web\Controller->renderTemplate('services/_entry', Array)
#28 [internal function]: craft\controllers\TemplatesController->actionRender('services/_entry', Array)
#29 /home/client/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#30 /home/client/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#31 /home/client/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('render', Array)
#32 /home/client/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#33 /home/client/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('templates/rende...', Array)
#34 /home/client/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#35 /home/client/vendor/craftcms/cms/src/web/Application.php(271): yii\web\Application->handleRequest(Object(craft\web\Request))
#36 /home/client/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#37 /home/client/public_html/index.php(21): yii\base\Application->run()
#38 {main}```

**Comment by mmikkel** [comment]
Hi @RitterKnightCreative – you're running into one of the few breaking API changes in Retcon 2.x, and unfortunately the docs are not up to date (I'll get to it ASAP, but busy days).

The signature for `retconSrcset` has changed – the new `selector` parameter is actually the second parameter – not the third, making `sizes` the third parameter.

In other words, this should do the trick:

```
{{ entry.body|retconSrcset(
    [
        {width: 375},
        {width: 480},
        {width: 768}
    ],
    'img',
    '(min-width: 40em) 80vw, 100vw'
) }}
```

Note: I also stumbled on (and fixed!) a different bug related to image transforms while I did some testing for your issue – so you might want to update to [the latest release](https://github.com/mmikkel/Retcon-Craft/releases/tag/2.0.6), too :)

**Comment by RitterKnightCreative** [comment]
@mmikkel great, thank you that worked! 

Seems to work fine within a regular redactor instance but if it's in a matrix block, I'm still seeing some breakage. (At least those cases are few and far between...)

**Comment by mmikkel** [comment]
What kind of breakage? :)

**Comment by RitterKnightCreative** [comment]
OK so did a little more investigating. Client had a block with some empty content. Didn't affect anything else but Retcon was breaking on null.

**Comment by mmikkel** [comment]
@RitterKnightCreative Thanks! That's weird though – if Retcon is fed `false`, `null` or an empty string it's supposed to just return an empty string.

I'll do some more testing, but to clarify; it was an empty Redactor field that caused the error?

**Comment by RitterKnightCreative** [comment]
Yeah, empty Redactor.  Could be Craft doing something funky as well but threw me for a loop when I saw it.

Here's the trace...

```
TypeError: Argument 1 passed to mmikkel\retcon\services\RetconService::srcset() must be of the type string, null given, called in /home/client/storage/runtime/compiled_templates/6d/6d34ac978d60928f04bedfb92052c2cc6f64f800c11359a25f7330448bdc212b.php on line 58 and defined in /home/client/vendor/mmikkel/retcon/src/services/RetconService.php:150
Stack trace:
#0 /home/client/storage/runtime/compiled_templates/6d/6d34ac978d60928f04bedfb92052c2cc6f64f800c11359a25f7330448bdc212b.php(58): mmikkel\retcon\services\RetconService->srcset(NULL, Array, 'img', '(min-width: 40e...')
#1 /home/client/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_6d0c7da2d2758d90932d6050daa7628ac2ca483c0d1b0b0ad8b187b3be45a442->doDisplay(Array, Array)
#2 /home/client/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#3 /home/client/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#4 /home/client/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#5 /home/client/storage/runtime/compiled_templates/21/2196f056b9c9f63f5d8d5c31c2945f59325a47edb61df4ca30739ed421821ba7.php(51): craft\web\twig\Template->display(Array)
#6 /home/client/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_ad2a5e94eea95a9d8ee225f46c717790ed75e389b8205d410a1cb2009662602b->block_content(Array, Array)
#7 /home/client/storage/runtime/compiled_templates/37/37abbda5ac6a809e6bae8dfaacb52a51db62fd35806c484b954befd18720c1cc.php(890): Twig_Template->displayBlock('content', Array, Array)
#8 /home/client/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_8e75b195c4c7e0a6e0464daa30863fde4e1cfec36948495a41f80552a7f05440->doDisplay(Array, Array)
#9 /home/client/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#10 /home/client/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#11 /home/client/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#12 /home/client/storage/runtime/compiled_templates/21/2196f056b9c9f63f5d8d5c31c2945f59325a47edb61df4ca30739ed421821ba7.php(28): craft\web\twig\Template->display(Array, Array)
#13 /home/client/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_ad2a5e94eea95a9d8ee225f46c717790ed75e389b8205d410a1cb2009662602b->doDisplay(Array, Array)
#14 /home/client/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#15 /home/client/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#16 /home/client/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#17 /home/client/vendor/twig/twig/lib/Twig/Template.php(375): craft\web\twig\Template->display(Array)
#18 /home/client/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#19 /home/client/vendor/craftcms/cms/src/web/View.php(330): Twig_Environment->render('companies/_entr...', Array)
#20 /home/client/vendor/craftcms/cms/src/web/View.php(377): craft\web\View->renderTemplate('companies/_entr...', Array)
#21 /home/client/vendor/craftcms/cms/src/web/Controller.php(155): craft\web\View->renderPageTemplate('companies/_entr...', Array)
#22 /home/client/vendor/craftcms/cms/src/controllers/TemplatesController.php(78): craft\web\Controller->renderTemplate('companies/_entr...', Array)
#23 [internal function]: craft\controllers\TemplatesController->actionRender('companies/_entr...', Array)
#24 /home/client/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#25 /home/client/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#26 /home/client/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('render', Array)
#27 /home/client/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#28 /home/client/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('templates/rende...', Array)
#29 /home/client/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#30 /home/client/vendor/craftcms/cms/src/web/Application.php(271): yii\web\Application->handleRequest(Object(craft\web\Request))
#31 /home/client/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#32 /home/client/public_html/index.php(21): yii\base\Application->run()
#33 {main}

**Comment by mmikkel** [comment]
@RitterKnightCreative Thanks for the stack trace!

I actually didn't account for Redactor fields returning `NULL` in some instances. Fixed in [v. 2.0.7](https://github.com/mmikkel/Retcon-Craft/releases/tag/2.0.7) and that exception shouldn't happen any more.

**Comment by RitterKnightCreative** [comment]
You rock sir.

**Comment by LouisCuvelier** [comment]
Hi,

I want just let you know that the [wiki](https://github.com/mmikkel/Retcon-Craft/wiki/srcset) is still not up to date 😉

Thanks for the plugin !
